export const CATEGORIES_PER_ROUND = 6;
export const CLUES_PER_CATEGORY = 5;
export const ROUNDS_PER_GAME = 2;

export const SINGLE_ROUND_VALUE_INCREMENT = 200;
export const DOUBLE_ROUND_VALUE_INCREMENT = 2 * SINGLE_ROUND_VALUE_INCREMENT;
